---
version: "3.9"
services:
  server:
    image: python:3
    ports:
      - 8000:8000
    command: python -m http.server
    container_name: server
    volumes:
      - test_volume:/tmp


volumes:
  test_volume:
    name: ${TEST_VOLUME}
