"3.7":
  docker_args:
    BASE_IMAGE: python:3.7-slim
"3.8":
  docker_args:
    BASE_IMAGE: python:3.8-slim
"3.9":
  docker_args:
    BASE_IMAGE: python:3.9-slim
"3.10":
  docker_args:
    BASE_IMAGE: python:3.10-slim
"3.11":
  docker_args:
    BASE_IMAGE: python:3.11-slim
