FROM python:3.7-slim

# COPY ./python_modules/ /tmp/python_modules/

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance

# Add repository code

WORKDIR /opt/dagster/app

COPY ../Dockerfile_user_code /opt/dagster/app

RUN pip install -r /opt/dagster/app/requirements.txt

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-d", "/opt/dagster/app"]
